### ISSUE TITLE
Does toyeca-cutter.awk also works on tab delimted files?

### ISSUE THREAD

**Issue by Ni-Ar** [rohitprajapati/toyeca-cutter#1]
Hi, title says it all! :)

**Comment by Ni-Ar** [comment]
Hi again, 

I just changed line 3 to `"\t"` and it works very smoothly.

```
BEGIN {
	FS = "\t"
}

````

Thanks for sharing this mini awk utility!
Nicco

**Comment by rohitprajapati** [comment]
Welcome 😃
